// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function GetInstallPath() {
  return window['go']['main']['App']['GetInstallPath']();
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenLogFile() {
  return window['go']['main']['App']['OpenLogFile']();
}

export function StartInstall() {
  return window['go']['main']['App']['StartInstall']();
}
