// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel():Promise<void>;

export function GetInstallPath():Promise<string>;

export function GetLogPath():Promise<string>;

export function GetVersion():Promise<string>;

export function OpenLogFile():Promise<void>;

export function StartInstall():Promise<void>;
